spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/hello-spring
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
